version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:7.10.1-browsers
    steps:
      - checkout
      - run: npm ci
      - run: npm run test
workflows:
  node-tests:
    jobs:
      - test
