version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:15.5.1-browsers
    steps:
      - checkout
      - run: npm i
      - run: npm run test
workflows:
  node-tests:
    jobs:
      - test
